### PR TITLE
fix verbose output

### PR DESCRIPTION
**Pull request by ambar**
https://github.com/mapbox/svg-react-transformer-writer/blob/master/bin/svg-react-transformer.js#L68

### CODE REVIEW

**Comment by davidtheclark** [comment]
@ambar Thanks for the contribution. Can you please explain what problem you're solving, and include a test to protect against regressions?

**Comment by ambar** [comment]
@davidtheclark test added.

**Comment by davidtheclark** [comment]
@ambar Thanks! It looks like you are fixing a bug that caused the verbose output to have incomplete JS filenames. Is that correct? I'd like to clarify so I can write a changelog entry and make sure I understand.

**Comment by ambar** [comment]
@davidtheclark Yes, it's empty, the `--verbose` flag had no effect before this patch.

**Comment by davidtheclark** [comment]
Published in 1.0.2. Thanks again @ambar, for diagnosing and fixing the problem.

**Pull request merged**
